In [1]:
import numpy as np
import scipy.io.wavfile
from scipy.fftpack import dct
get_ipython().run_line_magic('matplotlib', 'inline')
import matplotlib.pyplot as plt
import string
import pandas as pd
import glob 
import os
import random
import librosa


In [2]:
def parser(row):
    file_name = os.path.join("six_sec_glass", 'Train ('+ str(row) + ')'+'.wav')
    try:
        Y, sample_rate = librosa.load(file_name, res_type='kaiser_fast',sr=16000,mono=True) 
        pre_emphasis = 2
        X = np.append(Y[0], Y[1:] - pre_emphasis * Y[:-1])
        stft = np.abs(librosa.stft(X,n_fft=512,hop_length=168,win_length=500))
        mfccs = np.mean(librosa.feature.mfcc(y=X, sr=sample_rate, n_mfcc=64).T,axis=0) 
        contrast = np.mean(librosa.feature.spectral_contrast(S=stft, sr=sample_rate).T,axis=0)
        tonnetz = np.mean(librosa.feature.tonnetz(y=librosa.effects.harmonic(X),sr=sample_rate).T,axis=0)
        mel = np.mean(librosa.feature.melspectrogram(X, sr=sample_rate).T,axis=0)
        chroma = np.mean(librosa.feature.chroma_stft(S=stft, sr=sample_rate).T,axis=0)
    except Exception as e:
        print("Error encountered while parsing file: ", file)
        return None, None
    
    print(row)
    return mfccs,mel,contrast,tonnetz,row


In [3]:
def parser2(row):
    file_name = os.path.join("special_metal", 'metal'+ str(row) + '.wav')
    try:
        Y, sample_rate = librosa.load(file_name, res_type='kaiser_fast',sr=16000,mono=True) 
        pre_emphasis = 2
        X = np.append(Y[0], Y[1:] - pre_emphasis * Y[:-1])
        stft = np.abs(librosa.stft(X,n_fft=512,hop_length=168,win_length=500))
        mfccs = np.mean(librosa.feature.mfcc(y=X, sr=sample_rate, n_mfcc=64).T,axis=0) 
        contrast = np.mean(librosa.feature.spectral_contrast(S=stft, sr=sample_rate).T,axis=0)
        tonnetz = np.mean(librosa.feature.tonnetz(y=librosa.effects.harmonic(X),sr=sample_rate).T,axis=0)
        mel = np.mean(librosa.feature.melspectrogram(X, sr=sample_rate).T,axis=0)
        chroma = np.mean(librosa.feature.chroma_stft(S=stft, sr=sample_rate).T,axis=0)
    except Exception as e:
        print("Error encountered while parsing file: ", file)
        return None, None
    
    print(row)
    return mfccs,chroma,contrast,tonnetz,row

In [4]:
def feature():
    features=np.empty((0,65))
    label=np.empty((0,1))
    for i in range(1,200):
        mfccs,chroma,contrast,tonnetz,l=parser(i)
        ext_features = np.hstack([mfccs,chroma,contrast,tonnetz])
        features = np.vstack([features,ext_features])
        label=np.vstack((label,1))

    for i in range(1,200:
        mfccs,chroma,contrast,tonnetz,l=parser2(i)
        ext_features = np.hstack([mfccs,chroma,contrast,tonnetz])
        features = np.vstack([features,ext_features])
        label=np.vstack((label,0))
    
    return features,label

In [30]:
f=np.load('f_mfcc_128.npy')
l=np.load('l_mfcc_128.npy')

In [31]:
import sklearn
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report
from sklearn.ensemble import RandomForestRegressor

In [32]:
clf = SVC(C= 5, degree= 2, gamma= 0.0001, kernel= 'rbf', probability=True)
clf.fit(f, l.ravel())

SVC(C=5, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=2, gamma=0.0001, kernel='rbf',
  max_iter=-1, probability=True, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [82]:
rf = RandomForestRegressor(n_estimators = 1000, random_state = 100)
rf.fit(f, l.ravel())

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=1000, n_jobs=None,
           oob_score=False, random_state=100, verbose=0, warm_start=False)

In [8]:
print(l.shape)

(2234, 1)


In [31]:
file_name = os.path.join("metal_new", 'utensil5' + '.wav')
t, sample_rate = librosa.load(file_name,sr=16000,mono=True) 

In [27]:
pre_emphasis = 2
X = np.append(t[0], t[1:] - pre_emphasis * t[:-1])
stft = np.abs(librosa.stft(X,n_fft=512,hop_length=168,win_length=500))
mfccs = np.mean(librosa.feature.mfcc(y=X, sr=sample_rate, n_mfcc=40).T,axis=0) 
contrast = np.mean(librosa.feature.spectral_contrast(S=stft, sr=sample_rate).T,axis=0)
tonnetz = np.mean(librosa.feature.tonnetz(y=librosa.effects.harmonic(X),sr=sample_rate).T,axis=0)
mel = np.mean(librosa.feature.melspectrogram(X, sr=sample_rate).T,axis=0)
chroma = np.mean(librosa.feature.chroma_stft(S=stft, sr=sample_rate).T,axis=0)
spectral_centroids = np.mean(librosa.feature.spectral_centroid(X, sr=sample_rate).T,axis=0)
spectral_rolloff =  np.mean(librosa.feature.spectral_rolloff(X, sr=sample_rate).T,axis=0)

In [28]:
features_t=np.empty((0,40))
#ext_features_t = np.hstack([mfccs,chroma,mel])
features_t = np.vstack([features_t,mfccs])


In [29]:
print(l.shape)
print(l)

(2198, 1)
[[1.]
 [1.]
 [1.]
 ...
 [0.]
 [0.]
 [0.]]


In [30]:
clf.predict(features_t)

array([1.])

In [33]:
def parser3(row):
    file_name = os.path.join("three_sec_glass", 'testi ('+ str(row)+')' + '.wav')
    try:
        Y, sample_rate = librosa.load(file_name, res_type='kaiser_fast',sr=16000,mono=True) 
        pre_emphasis = 2
        X = np.append(Y[0], Y[1:] - pre_emphasis * Y[:-1])
        stft = np.abs(librosa.stft(X,n_fft=512,hop_length=168,win_length=500))
        mfccs = np.mean(librosa.feature.mfcc(y=X, sr=sample_rate, n_mfcc=128).T,axis=0) 
        zcr = np.mean(librosa.feature.zero_crossing_rate(X, frame_length=512, hop_length=168, center=True).T,axis=0) 
        rms=np.mean(librosa.feature.rms(X, frame_length=512, hop_length=168, center=True, pad_mode='reflect').T,axis=0)
        sc = np.mean(librosa.feature.spectral_centroid(X, sr=sample_rate).T,axis=0)
        sr =  np.mean(librosa.feature.spectral_rolloff(X, sr=sample_rate).T,axis=0)
    except Exception as e:
        print("Error encountered while parsing file: ", file)
        return None, None
    
    print(row)
    return mfccs,sc,sr

In [34]:
def parser4(row):
    file_name = os.path.join("special_metal", 'meta ('+ str(row)+')' + '.wav')
    try:
        Y, sample_rate = librosa.load(file_name, res_type='kaiser_fast',sr=16000,mono=True) 
        pre_emphasis = 2
        X = np.append(Y[0], Y[1:] - pre_emphasis * Y[:-1])
        stft = np.abs(librosa.stft(X,n_fft=512,hop_length=168,win_length=500))
        mfccs = np.mean(librosa.feature.mfcc(y=X, sr=sample_rate, n_mfcc=128).T,axis=0) 
        zcr = np.mean(librosa.feature.zero_crossing_rate(X, frame_length=512, hop_length=168, center=True).T,axis=0) 
        rms=np.mean(librosa.feature.rms(X, frame_length=512, hop_length=168, center=True, pad_mode='reflect').T,axis=0)
        sc = np.mean(librosa.feature.spectral_centroid(X, sr=sample_rate).T,axis=0)
        sr =  np.mean(librosa.feature.spectral_rolloff(X, sr=sample_rate).T,axis=0)
    except Exception as e:
        print("Error encountered while parsing file: ", file)
        return None, None
    
    print(row)
    return mfccs,sc,sr

In [35]:
def feature_test():
    features=np.empty((0,128))
    y_test=np.empty((0,1))
    for i in range(1,200):
        mfccs,sc,sr=parser3(i)
        ext_features = np.hstack([mfccs,sc,sr])
        features = np.vstack([features,mfccs])
        y_test=np.vstack((y_test,0))
      
    return features,y_test

In [36]:
def feature_test1():
    features=np.empty((0,128))
    y_test=np.empty((0,1))
    for i in range(1,150):
        mfccs,sc,sr=parser4(i)
        ext_features = np.hstack([mfccs,sc,sr])
        features = np.vstack([features,mfccs])
        y_test=np.vstack((y_test,0))
      
    return features,y_test

In [37]:
test_feature,y_test=feature_test()

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199


In [38]:
test_f,test_l=feature_test1()

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149


In [39]:
clf.predict(test_feature)
#print(y_test.shape)

array([1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1.,
       1., 0., 1., 1., 0., 1., 0., 0., 1., 1., 0., 0.])

In [157]:
prob=clf.predict_proba(test_feature)
new_list=[]

for i in range(prob.shape[0]):
    if prob[i][1]<0.4:
        new_list.append(0)
    else:
        new_list.append(1)
print(new_list)     
np.unique(new_list,return_counts=True)

[1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1]


(array([0, 1]), array([ 3, 10], dtype=int64))

In [23]:
clf.predict_proba(test_f)

array([[7.94414127e-01, 2.05585873e-01],
       [7.68589855e-01, 2.31410145e-01],
       [7.72093076e-01, 2.27906924e-01],
       [8.89903637e-01, 1.10096363e-01],
       [9.61666812e-01, 3.83331883e-02],
       [4.05304201e-01, 5.94695799e-01],
       [9.70184425e-01, 2.98155754e-02],
       [9.04460263e-01, 9.55397368e-02],
       [9.96699959e-01, 3.30004080e-03],
       [8.09708402e-01, 1.90291598e-01],
       [5.94418410e-01, 4.05581590e-01],
       [9.99738749e-01, 2.61251247e-04],
       [9.96360959e-01, 3.63904052e-03],
       [5.46383514e-01, 4.53616486e-01],
       [9.26598076e-01, 7.34019237e-02],
       [9.90169013e-01, 9.83098727e-03],
       [1.43119636e-02, 9.85688036e-01],
       [2.15312695e-01, 7.84687305e-01],
       [1.50535368e-01, 8.49464632e-01],
       [2.78039494e-02, 9.72196051e-01],
       [3.00957568e-02, 9.69904243e-01],
       [2.31178162e-02, 9.76882184e-01],
       [5.39843598e-02, 9.46015640e-01],
       [2.53172706e-02, 9.74682729e-01],
       [2.677959

In [163]:
prob=clf.predict_proba(test_f)
new_list=[]

for i in range(prob.shape[0]):
    if prob[i][1]<0.8:
        new_list.append(0)
    else:
        new_list.append(1)
print(new_list)     
np.unique(new_list,return_counts=True)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


(array([0, 1]), array([94, 55], dtype=int64))

In [43]:
clf.predict(test_f)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 1.,
       0., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1.,
       1., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0., 1., 1., 0., 1., 0., 0.,
       0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [117]:
predictions = clf.predict(test_feature)
# Calculate the absolute errors
errors = abs(predictions - y_test)
# Print out the mean absolute error (mae)
print('Mean Absolute Error:', round(np.mean(errors), 2), 'degrees.')

Mean Absolute Error: 0.84 degrees.


In [96]:
mape = 100 * (errors / y_test)
accuracy = 100 - np.mean(mape)
print('Accuracy:', round(accuracy, 2), '%.')

Accuracy: nan %.


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [97]:
print(test_feature.shape)
print(y_test.shape)

(199, 42)
(199, 1)


In [41]:
acc = clf.score(test_feature, y_test)
print("acc=%0.5f" % acc)

acc=0.09045


In [42]:
acc = clf.score(test_f, test_l)
print("acc=%0.5f" % acc)

acc=0.77181


In [28]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report
X_train, X_test, y_train, y_test = train_test_split(f, l.ravel(), test_size=0.4, random_state=0)
# Set the parameters by cross-validation
tuned_parameters = [{'kernel': ['rbf','poly'], 'gamma': [1e-2,1e-3,1],'C': [0.01,0.1,1,5],'degree':[2,3]}]
                     
scores = ['precision', 'recall']

for score in scores:
    print("# Tuning hyper-parameters for %s" % score)
    print('')

    clf = GridSearchCV(SVC(), tuned_parameters, cv=5,scoring='%s_macro' % score)
    clf.fit(X_train, y_train)

    print("Best parameters set found on development set:")
    print('')
    print(clf.best_params_)
    print('')
    print("Grid scores on development set:")
    print('')
    means = clf.cv_results_['mean_test_score']
    stds = clf.cv_results_['std_test_score']
    for mean, std, params in zip(means, stds, clf.cv_results_['params']):
        print("%0.3f (+/-%0.03f) for %r"% (mean, std * 2, params))
    print('')
    print("Detailed classification report:")
    print('')
    print("The model is trained on the full development set.")
    print("The scores are computed on the full evaluation set.")
    print('')
    y_true, y_pred = y_test, clf.predict(X_test)
    print(classification_report(y_true, y_pred))
    print('')

# Tuning hyper-parameters for precision



C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\m

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\m

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\m

Best parameters set found on development set:

{'C': 0.01, 'degree': 2, 'gamma': 0.01, 'kernel': 'poly'}

Grid scores on development set:

0.255 (+/-0.000) for {'C': 0.01, 'degree': 2, 'gamma': 0.01, 'kernel': 'rbf'}
0.999 (+/-0.003) for {'C': 0.01, 'degree': 2, 'gamma': 0.01, 'kernel': 'poly'}
0.255 (+/-0.000) for {'C': 0.01, 'degree': 2, 'gamma': 0.001, 'kernel': 'rbf'}
0.999 (+/-0.003) for {'C': 0.01, 'degree': 2, 'gamma': 0.001, 'kernel': 'poly'}
0.255 (+/-0.000) for {'C': 0.01, 'degree': 2, 'gamma': 1, 'kernel': 'rbf'}
0.999 (+/-0.003) for {'C': 0.01, 'degree': 2, 'gamma': 1, 'kernel': 'poly'}
0.255 (+/-0.000) for {'C': 0.01, 'degree': 3, 'gamma': 0.01, 'kernel': 'rbf'}
0.999 (+/-0.003) for {'C': 0.01, 'degree': 3, 'gamma': 0.01, 'kernel': 'poly'}
0.255 (+/-0.000) for {'C': 0.01, 'degree': 3, 'gamma': 0.001, 'kernel': 'rbf'}
0.999 (+/-0.003) for {'C': 0.01, 'degree': 3, 'gamma': 0.001, 'kernel': 'poly'}
0.255 (+/-0.000) for {'C': 0.01, 'degree': 3, 'gamma': 1, 'kernel': 'rbf'}
0.9